### ISSUE TITLE
What version of Java do I need? Not listed in Installation.txt

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2012-GraPacc#10]
If I need a specific version of Java (e.g. 1.7) it would be nice to know when I attempt to install the tool. (Hence it should probably appear in the Installation.txt file)

I know Helios works with 7, I don't THINK it works with 8: http://eclipsesource.com/blogs/2014/03/25/eclipse-support-for-java-8/

**Comment by aneeshkher** [comment]
Done. Added in installation.txt.
