### ISSUE TITLE
No license listed for at least two pieces of software

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2012-GraPacc#2]
I do not see the license for Eclipse or GraPacc clearly marked. Minor issue, possibly related to #1 

What is the eclipse license? What is the tool license?

**Comment by aneeshkher** [comment]
Fixes #2. Eclipse license has been added to the licenses.txt file. Tool license not listed as I haven't received any license from the authors. I have not yet received any response from the authors. Closing.
