### ISSUE TITLE
Tool Not working as indicated in the paper

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2012-GraPacc#25]
I clicked on the line between the arraylist and the scanner and input 'Ctrl-Space'. When I selected a pattern (e.g. 54020), the code was not transformed. I tried again in another area with a different pattern (I do not remember the number) and it worked.

May be related to #7

**Comment by aneeshkher** [comment]
Fixed #25. Mentioned in the README that some of the patterns might not get inserted after selecting. However, the patterns offered are still valid patterns. Related to #7.
