### ISSUE TITLE
Unable to see patterns after initial transformation

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2012-GraPacc#26]
After I perform one transformation using the tool, any subsequent times I use 'Ctrl-Space' I do not see the list of patterns.

For example, I use one pattern, type a few more statements, then enter 'Ctrl-Space' after the new statements to use another pattern in the same class. However, I do not see any patterns listed. In one instance the line prior to the attempted code-completion was IDENTICAL to the line where I had previously (successfully) performed a code completion

**Comment by seelder** [comment]
I believe that is may be resolved by saving the file between transformations. If so, it might be good to note this in the README that is in the  VM

**Comment by aneeshkher** [comment]
You are right about saving the file. I was able to see the patterns after saving the file and pressing 'Ctrl + Space'. I've noted this in the README in point 9. Closing issue.
