### ISSUE TITLE
Unnecessary Software still installed and taking up space on launcher

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2012-GraPacc#3]
I would recommend removing unnecessary software (e.g. Libreoffice). Fully removing software that is not used and re-sizing the memory space will decrease the size of the VM. 

At a minimum unused software should not be visible the launcher on the left-hand side so that when a user minimizes the tool, they can find it again fairly easily.

**Comment by aneeshkher** [comment]
Removed LibreOffice and Amazon Webapp.
