### ISSUE TITLE
Video does not open automatically

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2012-GraPacc#4]
When I selected the youtube video link a popup appeared asking if I want to run it in a terminal, view or run. Ideally it would automatically open firefox without the intermediate step. 

There may be multiple ways to accomplish this, but I did mine using a .desktop file (http://askubuntu.com/questions/359492/create-a-shortcut-for-url)

**Comment by aneeshkher** [comment]
Done. Thank you for the link.
